version: "3.7"

services:
    mongo:
        image: mongo:4.2.14-bionic
        restart: always
        ports: 
            - "27017:27017"
    crud:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        links: 
            - mongo
