version: "3.7"

services:

    postgres:
        image: postgres:12.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "12345"
            PGDATA: /var/lib/postgresql/data/pgdata

    nginx:
        image: nginx:1.18.0-alpine
            volumes:
                - ./templates:/etc/nginx/templates
            ports:
                - "8081:80"
            environment:
                - NGINX_HOST=ngin-docker.com
                - NGINX_PORT=80
        links:
            - postgres
