version: "3.7"

services:

    postgres:
        image: postgres:12.6
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "12345"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes: 
            - postgres_data: /var/postgresql/data
    
    django_app:
        build: .
        volumes: 
            - static: /code/static
            - .:/code
        depends_on: 
            - postgres

    nginx:
        image: nginx:1.18.0-alpine
        volumes:
            - ./templates:/etc/nginx/templates
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static:/code/static
        ports:
            - "8081:80"
        environment:
            - NGINX_HOST=ngin-docker.com
            - NGINX_PORT=80
        links:
            - postgres

volumes: 
    .:
    postgres_data:
    static: